# Generated by Django 4.0.4 on 2022-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='done',
        ),
        migrations.RemoveField(
            model_name='status',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='status',
            name='working',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('working', 'working'), ('done', 'done')], default='todo', max_length=20),
        ),
    ]
